Garage/Controllers/LandingController.cs
using Garage.Models;
using Garage.Service;
using Garage.Utils;
using Garage.Utils.Security;
using Garage.ViewModels;
using Garage.ViewModels.ShoppingCart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Garage.Utils.AppEnumeration;

namespace Garage.Controllers
{
    public class LandingController : Controller
    {
        readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private readonly ProductService productService = new ProductService(); 
        private readonly ProductPostTrackService productPostTrackService = new ProductPostTrackService();
        private readonly ProductImageService productImageService = new ProductImageService();
        private readonly CategoryService categoryService = new CategoryService();
        private readonly UserService userService = new UserService();
        private readonly SchoolService schoolService = new SchoolService();
        private readonly SessionObjService sessionObjService = new SessionObjService();

        [AllowAnonymous]
        public ActionResult Index()
        {
            logger.Info("Landing Controller - Application Start Page Opening");
            var isAuthenticated = Request.IsAuthenticated ? "Request Is Authenticated" : "Request Is Unauthenticated";
            logger.Info("Landing Controller - "+ isAuthenticated);
            return View();
        }

        [AllowAnonymous]
        [HttpGet, ActionName("HomePage")]
        public ActionResult HomePage()
        {
           
            logger.Info("Landing Controller - Listing products in home page");
            var recentProductList = productService.GetAllPublishedProducts().OrderByDescending(p => p.CreatedDate).Take(8).ToList();
            var mostWatchedProductList = productService.GetAllPublishedProducts().Where(p => p.ViewCount > 0).OrderByDescending(p => p.ViewCount).Take(8).ToList();
            ViewBag.RecentProducts = getProductListView(recentProductList);
            ViewBag.MostWatchedProducts = getProductListView(mostWatchedProductList);
            ViewBag.ParentCategories = getParentCategory();
            return View();
        }

        [AllowAnonymous]
        [HttpGet, ActionName("HelpPage")]
        public ActionResult HelpPage()
        {
            logger.Info("Landing Controller - Opens Help Page");
            ViewBag.ParentCategories = getParentCategory();
            return View();
        }

        [AllowAnonymous]
        [HttpGet, ActionName("RecentProducts")]
        public ActionResult RecentProducts()
        {
            logger.Info("Landing Controller - Listing Recent products in recent prodcuts page");
            //nahyan on 29jan20
            //  var productList = productService.GetAllPublishedProducts().Where(p => p.CreatedDate > DateTime.Now.AddDays(-7)).OrderByDescending(p => p.CreatedDate).ToList();
          //  var productList = productService.GetAllPublishedProducts().OrderByDescending(p => p.CreatedDate).ToList();
            var productList = productService.GetAllPublishedProducts().OrderByDescending(p => p.CreatedDate).ThenBy(p => p.UnitValue).ToList();
          //  var productList1 = productService.GetAllPublishedProducts().OrderByDescending(p => p.UnitValue).ToList();
            ViewBag.RecentProducts = getProductListView(productList);
            ViewBag.ParentCategories = getParentCategory();
            return View();
        }

        //[AppAuthorize]
        [HttpGet, ActionName("MostWatchedProducts")]
        public ActionResult MostWatchedProducts()
        {
            logger.Info("Landing Controller - Listing most watched products in home page");
            var productList = productService.GetAllPublishedProducts().Where(p=>p.ViewCount > 0).OrderByDescending(p => p.ViewCount).Take(25).ToList();
            ViewBag.MostWatchedProducts = getProductListView(productList);
            ViewBag.ParentCategories = getParentCategory();
            return View();
        }

        [AllowAnonymous]
        [HttpPost, ActionName("SearchProducts")]
        public ActionResult SearchProducts(string searchString)
        {
            logger.Info("Landing Controller - Listing search products in search result page");
            List<Product> searchedProducts;

            if (!string.IsNullOrEmpty(searchString))
            {
                 searchedProducts = productService.GetAllPublishedProducts().Where(p => p.ProductName.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            }
            else
            {
                 searchedProducts = productService.GetAllPublishedProducts().ToList();
            }
            ViewBag.SearchedProducts = getProductListView(searchedProducts);
            ViewBag.SearchString = searchString;
            ViewBag.ParentCategories = getParentCategory();
            return View();
        }

        [AppAuthorize]
        [HttpGet, ActionName("Cart")]
        public ActionResult CartList()
        {
            logger.Info("Landing Controller - Displaying cart products in cart page");
            if (Session["Cart"] != null)
            {
                var cart = (ShoppingCart)Session["Cart"];
                Session["Cart"] = cart.UpdateProductFromSession(cart);
            }
            
            ViewBag.ParentCategories = getParentCategory();
            return View();
        }

        [AppAuthorize]
        [HttpGet, ActionName("WishList")]
        public ActionResult WishList()
        {
            logger.Info("Landing Controller - Displaying wishlist products in wish list page");
            if (Session["WishList"] != null)
            {
                var wishList = (ShoppingCart)Session["WishList"];
                Session["WishList"] =  wishList.UpdateProductFromSession(wishList);
            }
            ViewBag.ParentCategories = getParentCategory();
            return View(new AddToCartForm());
        }

        [AppAuthorize]
        [HttpGet, ActionName("CartItem")]
        public ActionResult CartItem()
        {
            logger.Info("Landing Controller - Displaying cart items to School Admins except PO");
            ViewBag.SchoolCartItems = getCartItemsByCrrentUserSchool(AppUtils.getCurrentUser());
            return View();
        }

        [AppAuthorize]
        [HttpGet, ActionName("cart-item-count")]
        public ActionResult GetCartItemCount()
        {
            logger.Info("Landing Controller - Getting Cart Item Count by Ajax Call");
            var cartItemCount = getCartItemCountByCrrentUserSchool(AppUtils.getCurrentUser());
            return Json(new { cartItemCount }, JsonRequestBehavior.AllowGet);
        }

        #region Help Methods

        private List<ProductListView> getProductListView(List<Product> productList) =>
            productList.ConvertAll(p =>
            {
                var school = schoolService.GetSchoolById(p.SchoolId??0);
                var postTrackList = productPostTrackService.GetPostTrackByProductId(p.Id);
                var principalTrackEntry = postTrackList.Where(pt => pt.UserRole == (int)UserRole.Principal).FirstOrDefault();
                var publishedDate = principalTrackEntry == null ? p.CreatedDate : principalTrackEntry.CreatedDate;
                return new ProductListView()
                {
                    Product = p,
                    imageIdList = productImageService.GetProductImageByProductId(p.Id).ConvertAll(pi => pi.Id),
                    SchoolCode = school.SchoolCode,
                    PublishedDate = publishedDate
                };
            });

        private List<Category> getParentCategory() => categoryService.GetAllCategories().Where(p => p.ParentCategoryId == null || p.ParentCategoryId == 0 && p.Active == Convert.ToBoolean(YNStatue.Yes) && p.Deleted == Convert.ToBoolean(YNStatue.No)).ToList();

        private List<SchoolCartItem> getCartItemsByCrrentUserSchool(CurrentUser currentUser)
        {
            var schoolCartItems = new List<SchoolCartItem>();
            var currentSchoolIctList = userService.GetAllUsers().Where(u => u.School == currentUser.school.Id && u.Role == (int)UserRole.ICTEngineer).ToList();
            var sessionObj = sessionObjService.GetAllsessionObjs().Where(s => currentSchoolIctList.Select(u => u.Id).Contains(s.UserId) && s.ObjType == (int)SessionObjType.Cart).ToList();
            if (sessionObj != null && sessionObj.Count > 0)
            {
                schoolCartItems = sessionObj.ConvertAll(s =>
                {
                    var product = productService.GetProductById(s.ProductId ?? 0);
                    var imageIdList = productImageService.GetProductImageByProductId(product.Id).ConvertAll(pi => pi.Id);
                    var orderQuantity = s.ProductQuantity ?? 0;
                    var orderValue = orderQuantity * product.UnitValue;
                    var IctName = userService.GetUserById(s.UserId).FullName;

                    return new SchoolCartItem()
                    {
                        Product = product,
                        ImageIdList = imageIdList,
                        OrderQuantity = orderQuantity,
                        OrderValue = orderValue??0,
                        IctName = IctName
                    };
                });

                return schoolCartItems;
            }
            return schoolCartItems;
        }

        private int getCartItemCountByCrrentUserSchool(CurrentUser currentUser)
        {
            var currentSchoolIctList = userService.GetAllUsers().Where(u => u.School == currentUser.school.Id && u.Role == (int)UserRole.ICTEngineer).ToList();
            var sessionObj = sessionObjService.GetAllsessionObjs().Where(s => currentSchoolIctList.Select(u => u.Id).Contains(s.UserId) && s.ObjType == (int)SessionObjType.Cart).ToList();

Garage/Views/Landing/Cart.cshtml
@using Garage.Models
@using Garage.ViewModels.ShoppingCart
@using Garage.Utils

@{
    Layout = "~/Views/Shared/_SchoolAdminLayout.cshtml";
}

@section header {
    @RenderPage("~/Views/Shared/_Header.cshtml")
}

@section sidemenu {
    @RenderPage("~/Views/Shared/_SideMenuSchoolAdmins.cshtml")
}

@{
    ViewBag.Title = "Cart";
    ShoppingCart cart = null;
    if (AppUtils.getCart() != null) { cart = AppUtils.getCart(); }
}

<div class="page_content">

    <div class="title_name category_title_top">Cart</div>

    @if (cart != null && cart.CartItems.Count > 0)
    {
        decimal grandTotal = 0;

        foreach (var cartItem in cart.CartItems.Values)
        {
            var city = (AppEnumeration.City)(Convert.ToInt32(cartItem.Product.City));
            <div class="card box-shadow mt-4 mb-4">
                <div class="card-body cardBodyPadding">
                    <div class="product_listCart">
                        <div class="row">
                            <div class="col-md-12 col-lg-6 list_product_grp">
                                <div class="product_img" data-toggle="modal" data-target="#myModal"><img src="@Url.Action("ProductImage", "FileApi", new { productImageId = cartItem.ProductImageId })"></div>
                                <div class="product_details">
                                    <div class="product_name" data-toggle="modal" data-target="#myModal"> @cartItem.Product.ProductName </div>
                                    <div class="product_dec">
                                        @cartItem.Product.Description
                                    </div>
                                    <div class="product_location">
                                        @cartItem.Product.Location, @city
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12 col-lg-6 list_product_grp2">
                                @{ var formId = "AddToWishListForm" + cartItem.Product.Id; }
                                @using (Html.BeginForm("AddToWishList", "Order", FormMethod.Post, new { role = "form", id = formId }))
                                {
                                    @Html.Hidden("ProductId", cartItem.Product.Id)
                                    @Html.Hidden("removeFromCart", true)
                                    @Html.Hidden("returnUrl", this.Request.RawUrl)

                                    <div class="product_qnt">
                                        Quantity
                                        @Html.TextBox("UserQuantity", cartItem.ProductOrderQuantity, new { @class = "quantiy_input cart-quantity", type = "number", min = "1", max = cartItem.Product.InStock, dataproductid = cartItem.Product.Id, onkeyup="updateValue(this)" })
                                    </div>
                                }

                                @{ var removeFormId = "RemoveFromCartForm" + cartItem.Product.Id; }
                                @using (Html.BeginForm("RemoveFromCart", "Order", FormMethod.Post, new { role = "form", id = removeFormId }))
                                {
                                    @Html.Hidden("productId", cartItem.Product.Id)
                                }
                                <div class="product_wishlist">
                                    @{ 
                                        var subTotal = cartItem.ProductOrderQuantity * cartItem.Product.UnitValue;
                                        grandTotal = grandTotal + (subTotal??0);
                                    }
                                    <span class="d-none" id="unitValue@(cartItem.Product.Id)">@cartItem.Product.UnitValue</span>
                                    <span class="totalbox">Sub-total: AED <span class="subtotal" id="subTotal@(cartItem.Product.Id)">@subTotal</span> </span>
                                    <span class="pr-3"><a class="wish_list" href="#" onclick="document.getElementById('@removeFormId').submit();">Remove</a></span>
                                    <a class="wish_list" href="#" onclick="document.getElementById('@formId').submit();">Move to wish list</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        }

        <div class="show_all">
            <span class="totalbox">Total: AED <span id="grandTotal">@grandTotal</span></span>
            <a class="btn btn-primary" href="#" onclick="submitOrder();">CHECK OUT</a>
        </div>

    }
    else
    {
        <div class="no_data_set">
            <img src="~/Content/assets/images/no_cart.svg" class="img-fluid">
            <div class="text-center no_data_txt">Sorry, no products to display!</div>
            <div class="text-center">Please try searching for something else</div>
        </div>
    }

</div>
@section footerscript {

    <script type="text/javascript">

        var orderUrl = '@Url.Action("Checkout","Order")';

        function submitOrder() {
            var productItems = [];
            $(".cart-quantity").each(function () {
                var productId = $(this).attr("dataproductid");
                var quantity = $(this).val();
                var productItem = {
                    productId,
                    quantity
                }
                productItems.push(productItem);
            });
           // console.log(productItems);

            jQuery.ajax({
                url: orderUrl,
                type: "POST",
                data: { productOrderForm: productItems },
                beforeSend: function (x) {
                    //if (x && x.overrideMimeType) {
                    //    x.overrideMimeType("application/j-son;charset=UTF-8");
                    //}
                },
                success: function (result) {
                    //if (!result.isValid) { alert("Somthing went wrong"); }
                    window.location.href = "/Order/Orders";
                    //Write your code here
                }
            });
        }

        function updateValue(obj) {
            var quantity = $(obj).val();
            var productId = $(obj).attr("dataproductid");
            var maxQuantity = Number($(obj).attr("max"));
            var unitValue = $("#unitValue" + productId).text();
            if (quantity == undefined || quantity == '' || quantity == null) {
                quantity = 0;
                $(obj).val(quantity);
            } else if (quantity > maxQuantity) {
                quantity = maxQuantity;
                $(obj).val(quantity);
            } else {

            }
            var subTotal = Number(quantity) * Number(unitValue);
            $("#subTotal" + productId).text(subTotal);
            var grandTotal = 0;
            $(".subtotal").each(function () {
                grandTotal = grandTotal + Number($(this).text());
            });
            $("#grandTotal").text(grandTotal);
        }

    </script>

}

Garage/Views/Landing/CartItem.cshtml
@using Garage.Models
@using Garage.ViewModels.ShoppingCart
@using Garage.Utils
@using Garage.ViewModels

@{
    Layout = "~/Views/Shared/_SchoolAdminLayout.cshtml";
}

@section header {
    @RenderPage("~/Views/Shared/_Header.cshtml")
}

@section sidemenu {
    @RenderPage("~/Views/Shared/_SideMenuSchoolAdmins.cshtml")
}

@{
    ViewBag.Title = "Cart";
    var cartItems = (List<SchoolCartItem>)ViewBag.SchoolCartItems;
}

    <div class="page_content">

        <div class="title_name category_title_top">Order Draft</div>

        @if (cartItems != null && cartItems.Count > 0)
        {
            foreach (var cartItem in cartItems)
            {
                <div class="card box-shadow mt-4 mb-4">
                    <div class="card-body cardBodyPadding">
                        <div class="product_listCart">
                            <div class="row">
                                <div class="col-md-12 col-lg-8 list_product_grp">
                                    <div class="product_img" data-toggle="modal" data-target="#myModal"><img src="@Url.Action("ProductImage", "FileApi", new { productImageId = cartItem.ImageIdList.FirstOrDefault() })"></div>
                                    <div class="product_details">
                                        <div class="product_name" data-toggle="modal" data-target="#myModal">@cartItem.Product.ProductName</div>
                                        <div class="school_name">
                                            Product School Name: <b>@cartItem.Product.Location</b>
                                        </div>
                                        <div class="school_name">
                                            Location / City: <b>@(EnumHelper<AppEnumeration.City>.GetDisplayValue((AppEnumeration.City)cartItem.Product.City))</b>
                                        </div>
                                        <div class="product_location">
                                            ICT Name: @cartItem.IctName
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 col-lg-4 pt-4">
                                    <div class="value_set">
                                        <div class="value_draft">
                                            <div class="value_lable">Order Quantity: </div>
                                            <div class="value_data">@cartItem.OrderQuantity</div>
                                        </div>
                                        <div class="value_draft">
                                            <div class="value_lable">Unit Value: </div>
                                            <div class="value_data">@cartItem.Product.UnitValue AED</div>
                                        </div>
                                        <div class="value_draft">
                                            <div class="value_lable">Order Value: </div>
                                            <div class="value_data">@cartItem.OrderValue AED</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="draft_description">
                                <div class="draft_description_lable">Description :</div>
                                <div class="draft_description_data">@cartItem.Product.Description</div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="draft_bottom_total">
                <div class="draft_grand_total">Grand Total: <b>@(cartItems.Sum(c => c.OrderValue))</b></div>
            </div>
        }
        else
        {
            <div class="no_data_set">
                <img src="~/Content/assets/images/no_cart.svg" class="img-fluid">
                <div class="text-center no_data_txt">Sorry, no products to display!</div>
                @*<div class="text-center">Please try searching for something else</div>*@
            </div>
        }

    </div>
@section footerscript {

    <script type="text/javascript">

        var orderUrl = '@Url.Action("Checkout","Order")';

        function submitOrder() {
            var productItems = [];
            $(".cart-quantity").each(function () {
                var productId = $(this).attr("dataproductid");
                var quantity = $(this).val();
                var productItem = {
                    productId,
                    quantity
                }
                productItems.push(productItem);
            });
           // console.log(productItems);

            jQuery.ajax({
                url: orderUrl,
                type: "POST",
                data: { productOrderForm: productItems },
                beforeSend: function (x) {
                    //if (x && x.overrideMimeType) {
                    //    x.overrideMimeType("application/j-son;charset=UTF-8");
                    //}
                },
                success: function (result) {
                    //if (!result.isValid) { alert("Somthing went wrong"); }
                    window.location.href = "/Order/Orders";
                    //Write your code here
                }
            });
        }

        function updateValue(obj) {
            var quantity = $(obj).val();
            var productId = $(obj).attr("dataproductid");
            var maxQuantity = Number($(obj).attr("max"));
            var unitValue = $("#unitValue" + productId).text();
            if (quantity == undefined || quantity == '' || quantity == null) {
                quantity = 0;
                $(obj).val(quantity);
            } else if (quantity > maxQuantity) {
                quantity = maxQuantity;
                $(obj).val(quantity);
            } else {

            }
            var subTotal = Number(quantity) * Number(unitValue);
            $("#subTotal" + productId).text(subTotal);
            var grandTotal = 0;
            $(".subtotal").each(function () {
                grandTotal = grandTotal + Number($(this).text());
            });
            $("#grandTotal").text(grandTotal);
        }

    </script>

}

Garage/Views/Landing/HomePage.cshtml
@using System
@using Garage.Utils
@using Garage.ViewModels
@using Garage.Models

@{
    Layout = "~/Views/Shared/_EcommerceLayout.cshtml";
    CurrentUser currentUser = AppUtils.getCurrentUser();
}

@section header {
    @if (currentUser != null)
    {
        if (currentUser.isSuperAdmin)
        {
            @RenderPage("~/Views/Shared/_HeaderAdmin.cshtml")
        }
        else
        {
            @RenderPage("~/Views/Shared/_Header.cshtml")
        }
    }
    else
    {
        @RenderPage("~/Views/Shared/_HeaderVisitor.cshtml")
    }


}

@section sidemenu {
    @RenderPage("~/Views/Shared/_SideMenu.cshtml")
}
<style>
    .out-of-stock {
        background-image: url(../Content/assets/images/sold.png);
        background-repeat: no-repeat;
        width: 60px !important;
        height: 60px !important;
        background-size: contain;
        position: absolute;
        text-indent: -10000px;
    }
</style>
@section footerscript {
    <script>
        (function (global) {

            if (typeof (global) === "undefined") {
                throw new Error("window is undefined");
            }

            var _hash = "!";
            var noBackPlease = function () {
                global.location.href += "#";


                global.setTimeout(function () {
                    global.location.href += "!";
                }, 50);
            };

            // Earlier we had setInerval here....
            global.onhashchange = function () {
                if (global.location.hash !== _hash) {
                    global.location.hash = _hash;
                }
            };

            global.onload = function () {

                noBackPlease();

                // disables backspace on page except on input fields and textarea..
                document.body.onkeydown = function (e) {
                    var elm = e.target.nodeName.toLowerCase();
                    if (e.which === 8 && (elm !== 'input' && elm !== 'textarea')) {
                        e.preventDefault();
                    }
                    // stopping event bubbling up the DOM tree..
                    e.stopPropagation();
                };

            };

        })(window);
    </script>

}

@{
    ViewBag.Title = "Home Page";
    var recentProducts = (List<ProductListView>)ViewBag.RecentProducts;
    var mostWatchedProducts = (List<ProductListView>)ViewBag.MostWatchedProducts;
}

<div class="page_content">

    @*<div class="banner_image">
            <img class="img-fluid" src="~/Content/assets/images/1200x150.png" alt="">
        </div>*@

    <div class="title_name">Recently Added Assets</div>
    @if (recentProducts.Count > 0)
    {
        <div class="row">

            @foreach (var productView in recentProducts)
            {
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <div class="product_box product-view-pop" data-toggle="modal" data-url="@Url.Action("View","Product",new { id= productView.Product.Id})">
                        @if (productView.Product.InStock == 0)
                        {
                            <div class="out-of-stock">Out of Stock</div>
                        }
                        <div class="product_img">
                            <img class="img-fluid" src="@Url.Action("ProductImage","FileApi", new { productImageId = productView.imageIdList.FirstOrDefault() })" />
                        </div>
                        <div class="product_details">
                            <div class="product_name">
                                @productView.Product.ProductName
                            </div>
                            <div class="product_price">
                                <span>AED</span> @productView.Product.UnitValue
                            </div>
                        </div>
                        <div class="product_info">
                            <div class="product_info_line1">@productView.SchoolCode.ToUpper()</div>
                            <div class="product_info_line2">@(productView.PublishedDate.HasValue ? productView.PublishedDate.Value.ToString("dd-MM-yyyy") : "")</div>
                            <div class="product_info_line3"><img src="~/Content/images/stock.svg" /> @((int)productView.Product.InStock)</div>
                        </div>
                    </div>
                </div>
            }

        </div>
        if (recentProducts.Count > 0)
        {
            <div class="show_all"><a href="@Url.Action("RecentProducts","Landing")">Show All</a></div>
        }

    }
    else
    {

        <div class="no_data_set">
            <img src="~/Content/assets/images/no_category.svg" class="img-fluid">
            <div class="text-center no_data_txt">Sorry, no products to display!</div>
            <div class="text-center">Please try searching for something else</div>
        </div>
    }

    <div class="title_name">Most Watched Assets</div>

    <div class="row">

        @foreach (var productView in mostWatchedProducts)
        {
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                <div class="product_box product-view-pop" data-toggle="modal" data-url="@Url.Action("View","Product",new { id= productView.Product.Id})">
                    @if (productView.Product.InStock == 0)
                    {
                        <div class="out-of-stock">Out of Stock</div>
                    }
                    <div class="product_img">
                        <img class="img-fluid" src="@Url.Action("ProductImage","FileApi", new { productImageId = productView.imageIdList.FirstOrDefault() })" />
                    </div>
                    <div class="product_details">
                        <div class="product_name">
                            @productView.Product.ProductName
                        </div>
                        <div class="product_price">
                            <span>AED</span> @productView.Product.UnitValue
                        </div>
                    </div>
                    <div class="product_info">
                        <div class="product_info_line1">@productView.SchoolCode.ToUpper()</div>
                        <div class="product_info_line2">@(productView.PublishedDate.HasValue ? productView.PublishedDate.Value.ToString("dd-MM-yyyy") : "")</div>
                        <div class="product_info_line3"><img src="~/Content/images/stock.svg" /> @((int)productView.Product.InStock)</div>
                    </div>
                </div>
            </div>
        }
    </div>
    @if (mostWatchedProducts.Count > 0)
    {
        <div class="show_all"><a href="@Url.Action("MostWatchedProducts","Landing")">Show All</a></div>
    }

</div>